services:
  ldap:
    image: bitnami/openldap:latest
    ports:
      - '389:389'
    environment:
      - LDAP_ROOT=dc=example,dc=test
      - LDAP_SKIP_DEFAULT_TREE=yes
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_PORT_NUMBER=389
    volumes:
      - "./config/ldap/ldifs:/ldifs/:ro"
      - "./config/ldap/schemas:/schemas/:ro"

  ldap-ui:
    image: dnknth/ldap-ui
    build: .
    ports:
      - 127.0.0.1:5000:5000
    links:
      - ldap
    environment:
      LDAP_URL: "${LDAP_URL:-ldap://ldap/}"
      USE_TLS: ${USE_TLS:-}
      INSECURE_TLS: ${INSECURE_TLS:-}
      BASE_DN: "${BASE_DN:-dc=example,dc=test}"
      BIND_DN: "${BIND_DN:-uid=admin,dc=example,dc=test}"
      BIND_PASSWORD: "${BIND_PASSWORD:-admin}"
    restart: unless-stopped
    healthcheck:
      test: "wget -q -O /dev/null http://127.0.0.1:5000"
      interval: 30s
      retries: 2
      timeout: 2s
