[project]
site_name = "LDAP Password Change"
site_url = "https://marcel2603.github.io/github.com/Marcel2603/ldap-password-change/"
repo_url = "https://github.com/Marcel2603/ldap-password-change"
repo_name = "Marcel2603/ldap-password-change"
docs_dir = "pages"
extra_css = ["stylesheets/max_width.css"]
nav = [
  { "Home" = "index.md" },
  { "Getting Started" = [
    { "Overview" = "getting-started/index.md" },
    { "Customisation" = "getting-started/customisation.md" },
    { "Architecture" = "getting-started/architecture.md" },
    { "Health" = "getting-started/health.md" },
    { "Metrics" = "getting-started/metrics.md" },
    { "Usage" = "getting-started/usage.md" },
    { "Configuration" = [
      { "Overview" = "getting-started/configuration/index.md" },
      { "What" = "getting-started/configuration/what.md" },
      { "Where" = "getting-started/configuration/where.md" }
    ]}
  ]},
  { "Development" = [
    { "Overview" = "development/index.md" },
    { "Release" = "development/release.md" }
  ]},
  { "About" = [
    { "Security" = "about/security.md" },
    { "License" = "about/license.md" }
  ]}
]

[project.theme]
variant = "modern"
features = [
    "navigation.indexes",
    "navigation.instant",
    "navigation.tracking",
    "navigation.path",
    "search.suggest",
    "search.highlight",
    "content.code.copy",
    "content.code.annotate",
    "content.tabs.link",
]

[project.theme.font]
text = "Roboto"
code = "Roboto Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle = { icon = "material/brightness-auto", name = "Switch to light mode" }

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "white"
accent = "indigo"
toggle = { icon = "material/brightness-7", name = "Switch to dark mode" }

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
accent = "indigo"
toggle = { icon = "material/brightness-4", name = "Switch to system preference" }

[project.markdown]
extensions = [
    "admonition",
    "codehilite",
    "footnotes",
    "tables"
]

[project.markdown.toc]
permalink = true

[project.plugins]
search = {}
autolinks = {}

[project.plugins.git-revision-date-localized]
fallback_to_build_date = true
